RECRUITMENT_RESUME_JSON_SCHEMA = {
    "name": "resume_parse_result",
    "schema": {
        "type": "object",
        "additionalProperties": False,
        "required": [
            "candidate",
            "skills",
            "project_experiences",
            "work_experiences",
            "certificates",
            "resume_summary",
            "strengths",
            "risks",
            "suggested_interview_questions",
            "confidence",
            "need_manual_review",
            "warnings",
        ],
        "properties": {
            "candidate": {
                "type": "object",
                "additionalProperties": False,
                "required": [
                    "name",
                    "phone",
                    "email",
                    "education",
                    "school",
                    "major",
                    "graduation_year",
                    "work_years",
                ],
                "properties": {
                    "name": {"type": ["string", "null"]},
                    "phone": {"type": ["string", "null"]},
                    "email": {"type": ["string", "null"]},
                    "education": {"type": ["string", "null"]},
                    "school": {"type": ["string", "null"]},
                    "major": {"type": ["string", "null"]},
                    "graduation_year": {"type": ["string", "null"]},
                    "work_years": {"type": ["string", "null"]},
                },
            },
            "skills": {"type": "array", "items": {"type": "string"}},
            "project_experiences": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["project_name", "role", "tech_stack", "responsibilities", "outcomes"],
                    "properties": {
                        "project_name": {"type": ["string", "null"]},
                        "role": {"type": ["string", "null"]},
                        "tech_stack": {"type": "array", "items": {"type": "string"}},
                        "responsibilities": {"type": ["string", "null"]},
                        "outcomes": {"type": ["string", "null"]},
                    },
                },
            },
            "work_experiences": {
                "type": "array",
                "items": {
                    "type": "object",
                    "additionalProperties": False,
                    "required": ["company", "title", "start_time", "end_time", "responsibilities"],
                    "properties": {
                        "company": {"type": ["string", "null"]},
                        "title": {"type": ["string", "null"]},
                        "start_time": {"type": ["string", "null"]},
                        "end_time": {"type": ["string", "null"]},
                        "responsibilities": {"type": ["string", "null"]},
                    },
                },
            },
            "certificates": {"type": "array", "items": {"type": "string"}},
            "resume_summary": {"type": ["string", "null"]},
            "strengths": {"type": "array", "items": {"type": "string"}},
            "risks": {"type": "array", "items": {"type": "string"}},
            "suggested_interview_questions": {"type": "array", "items": {"type": "string"}},
            "confidence": {"type": "number", "minimum": 0, "maximum": 1},
            "need_manual_review": {"type": "boolean"},
            "warnings": {"type": "array", "items": {"type": "string"}},
        },
    },
    "strict": True,
}
